id = "vue-snippets"
name = "Vue Snippets"
version = "0.0.1"
schema_version = 1
authors = ["silvester wali <silvesterlhwali123@gmail.com>"]
description = "Vue snippets for the Zed IDE. A collection of Vue snippets to improve development speed."
repository = "https://github.com/silvesterwali/vue-snippets-for-zed"
snippets = "./snippets/vue.json"